USE [FindMySportsMate]
GO

/****** Object:  Table [dbo].[JoinedUser]    Script Date: 05/04/2012 03:34:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[JoinedUser](
	[UserId] [int] NOT NULL,
	[SuggestionId] [int] NOT NULL,
	[Weekdays] [varchar](50) NOT NULL,
 CONSTRAINT [PK_JoinedUser_1] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[SuggestionId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

